# CMAKE generated file: DO NOT EDIT!
# Generated by "Unix Makefiles" Generator, CMake Version 3.28

# Default target executed when no arguments are given to make.
default_target: all
.PHONY : default_target

# Allow only one "make -f Makefile2" at a time, but pass parallelism.
.NOTPARALLEL:

#=============================================================================
# Special targets provided by cmake.

# Disable implicit rules so canonical targets will work.
.SUFFIXES:

# Disable VCS-based implicit rules.
% : %,v

# Disable VCS-based implicit rules.
% : RCS/%

# Disable VCS-based implicit rules.
% : RCS/%,v

# Disable VCS-based implicit rules.
% : SCCS/s.%

# Disable VCS-based implicit rules.
% : s.%

.SUFFIXES: .hpux_make_needs_suffix_list

# Command-line flag to silence nested $(MAKE).
$(VERBOSE)MAKESILENT = -s

#Suppress display of executed commands.
$(VERBOSE).SILENT:

# A target that is always out of date.
cmake_force:
.PHONY : cmake_force

#=============================================================================
# Set environment variables for the build.

# The shell in which to execute make rules.
SHELL = /bin/sh

# The CMake executable.
CMAKE_COMMAND = /usr/bin/cmake

# The command to remove a file.
RM = /usr/bin/cmake -E rm -f

# Escaping for special characters.
EQUALS = =

# The top-level source directory on which CMake was run.
CMAKE_SOURCE_DIR = /workspaces/Game

# The top-level build directory on which CMake was run.
CMAKE_BINARY_DIR = /workspaces/Game

#=============================================================================
# Targets provided globally by CMake.

# Special rule for the target edit_cache
edit_cache:
	@$(CMAKE_COMMAND) -E cmake_echo_color "--switch=$(COLOR)" --cyan "No interactive CMake dialog available..."
	/usr/bin/cmake -E echo No\ interactive\ CMake\ dialog\ available.
.PHONY : edit_cache

# Special rule for the target edit_cache
edit_cache/fast: edit_cache
.PHONY : edit_cache/fast

# Special rule for the target rebuild_cache
rebuild_cache:
	@$(CMAKE_COMMAND) -E cmake_echo_color "--switch=$(COLOR)" --cyan "Running CMake to regenerate build system..."
	/usr/bin/cmake --regenerate-during-build -S$(CMAKE_SOURCE_DIR) -B$(CMAKE_BINARY_DIR)
.PHONY : rebuild_cache

# Special rule for the target rebuild_cache
rebuild_cache/fast: rebuild_cache
.PHONY : rebuild_cache/fast

# Special rule for the target list_install_components
list_install_components:
	@$(CMAKE_COMMAND) -E cmake_echo_color "--switch=$(COLOR)" --cyan "Available install components are: \"Unspecified\""
.PHONY : list_install_components

# Special rule for the target list_install_components
list_install_components/fast: list_install_components
.PHONY : list_install_components/fast

# Special rule for the target install
install: preinstall
	@$(CMAKE_COMMAND) -E cmake_echo_color "--switch=$(COLOR)" --cyan "Install the project..."
	/usr/bin/cmake -P cmake_install.cmake
.PHONY : install

# Special rule for the target install
install/fast: preinstall/fast
	@$(CMAKE_COMMAND) -E cmake_echo_color "--switch=$(COLOR)" --cyan "Install the project..."
	/usr/bin/cmake -P cmake_install.cmake
.PHONY : install/fast

# Special rule for the target install/local
install/local: preinstall
	@$(CMAKE_COMMAND) -E cmake_echo_color "--switch=$(COLOR)" --cyan "Installing only the local directory..."
	/usr/bin/cmake -DCMAKE_INSTALL_LOCAL_ONLY=1 -P cmake_install.cmake
.PHONY : install/local

# Special rule for the target install/local
install/local/fast: preinstall/fast
	@$(CMAKE_COMMAND) -E cmake_echo_color "--switch=$(COLOR)" --cyan "Installing only the local directory..."
	/usr/bin/cmake -DCMAKE_INSTALL_LOCAL_ONLY=1 -P cmake_install.cmake
.PHONY : install/local/fast

# Special rule for the target install/strip
install/strip: preinstall
	@$(CMAKE_COMMAND) -E cmake_echo_color "--switch=$(COLOR)" --cyan "Installing the project stripped..."
	/usr/bin/cmake -DCMAKE_INSTALL_DO_STRIP=1 -P cmake_install.cmake
.PHONY : install/strip

# Special rule for the target install/strip
install/strip/fast: preinstall/fast
	@$(CMAKE_COMMAND) -E cmake_echo_color "--switch=$(COLOR)" --cyan "Installing the project stripped..."
	/usr/bin/cmake -DCMAKE_INSTALL_DO_STRIP=1 -P cmake_install.cmake
.PHONY : install/strip/fast

# The main all target
all: cmake_check_build_system
	$(CMAKE_COMMAND) -E cmake_progress_start /workspaces/Game/CMakeFiles /workspaces/Game//CMakeFiles/progress.marks
	$(MAKE) $(MAKESILENT) -f CMakeFiles/Makefile2 all
	$(CMAKE_COMMAND) -E cmake_progress_start /workspaces/Game/CMakeFiles 0
.PHONY : all

# The main clean target
clean:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/Makefile2 clean
.PHONY : clean

# The main clean target
clean/fast: clean
.PHONY : clean/fast

# Prepare targets for installation.
preinstall: all
	$(MAKE) $(MAKESILENT) -f CMakeFiles/Makefile2 preinstall
.PHONY : preinstall

# Prepare targets for installation.
preinstall/fast:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/Makefile2 preinstall
.PHONY : preinstall/fast

# clear depends
depend:
	$(CMAKE_COMMAND) -S$(CMAKE_SOURCE_DIR) -B$(CMAKE_BINARY_DIR) --check-build-system CMakeFiles/Makefile.cmake 1
.PHONY : depend

#=============================================================================
# Target rules for targets named mechanica_imperii

# Build rule for target.
mechanica_imperii: cmake_check_build_system
	$(MAKE) $(MAKESILENT) -f CMakeFiles/Makefile2 mechanica_imperii
.PHONY : mechanica_imperii

# fast build rule for target.
mechanica_imperii/fast:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/mechanica_imperii.dir/build.make CMakeFiles/mechanica_imperii.dir/build
.PHONY : mechanica_imperii/fast

#=============================================================================
# Target rules for targets named test_enhanced_config

# Build rule for target.
test_enhanced_config: cmake_check_build_system
	$(MAKE) $(MAKESILENT) -f CMakeFiles/Makefile2 test_enhanced_config
.PHONY : test_enhanced_config

# fast build rule for target.
test_enhanced_config/fast:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/test_enhanced_config.dir/build.make CMakeFiles/test_enhanced_config.dir/build
.PHONY : test_enhanced_config/fast

#=============================================================================
# Target rules for targets named test_scenario_demo

# Build rule for target.
test_scenario_demo: cmake_check_build_system
	$(MAKE) $(MAKESILENT) -f CMakeFiles/Makefile2 test_scenario_demo
.PHONY : test_scenario_demo

# fast build rule for target.
test_scenario_demo/fast:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/test_scenario_demo.dir/build.make CMakeFiles/test_scenario_demo.dir/build
.PHONY : test_scenario_demo/fast

apps/main_minimal.o: apps/main_minimal.cpp.o
.PHONY : apps/main_minimal.o

# target to build an object file
apps/main_minimal.cpp.o:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/mechanica_imperii.dir/build.make CMakeFiles/mechanica_imperii.dir/apps/main_minimal.cpp.o
.PHONY : apps/main_minimal.cpp.o

apps/main_minimal.i: apps/main_minimal.cpp.i
.PHONY : apps/main_minimal.i

# target to preprocess a source file
apps/main_minimal.cpp.i:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/mechanica_imperii.dir/build.make CMakeFiles/mechanica_imperii.dir/apps/main_minimal.cpp.i
.PHONY : apps/main_minimal.cpp.i

apps/main_minimal.s: apps/main_minimal.cpp.s
.PHONY : apps/main_minimal.s

# target to generate assembly for a file
apps/main_minimal.cpp.s:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/mechanica_imperii.dir/build.make CMakeFiles/mechanica_imperii.dir/apps/main_minimal.cpp.s
.PHONY : apps/main_minimal.cpp.s

apps/test_enhanced_config.o: apps/test_enhanced_config.cpp.o
.PHONY : apps/test_enhanced_config.o

# target to build an object file
apps/test_enhanced_config.cpp.o:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/test_enhanced_config.dir/build.make CMakeFiles/test_enhanced_config.dir/apps/test_enhanced_config.cpp.o
.PHONY : apps/test_enhanced_config.cpp.o

apps/test_enhanced_config.i: apps/test_enhanced_config.cpp.i
.PHONY : apps/test_enhanced_config.i

# target to preprocess a source file
apps/test_enhanced_config.cpp.i:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/test_enhanced_config.dir/build.make CMakeFiles/test_enhanced_config.dir/apps/test_enhanced_config.cpp.i
.PHONY : apps/test_enhanced_config.cpp.i

apps/test_enhanced_config.s: apps/test_enhanced_config.cpp.s
.PHONY : apps/test_enhanced_config.s

# target to generate assembly for a file
apps/test_enhanced_config.cpp.s:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/test_enhanced_config.dir/build.make CMakeFiles/test_enhanced_config.dir/apps/test_enhanced_config.cpp.s
.PHONY : apps/test_enhanced_config.cpp.s

apps/test_scenario_demo.o: apps/test_scenario_demo.cpp.o
.PHONY : apps/test_scenario_demo.o

# target to build an object file
apps/test_scenario_demo.cpp.o:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/test_scenario_demo.dir/build.make CMakeFiles/test_scenario_demo.dir/apps/test_scenario_demo.cpp.o
.PHONY : apps/test_scenario_demo.cpp.o

apps/test_scenario_demo.i: apps/test_scenario_demo.cpp.i
.PHONY : apps/test_scenario_demo.i

# target to preprocess a source file
apps/test_scenario_demo.cpp.i:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/test_scenario_demo.dir/build.make CMakeFiles/test_scenario_demo.dir/apps/test_scenario_demo.cpp.i
.PHONY : apps/test_scenario_demo.cpp.i

apps/test_scenario_demo.s: apps/test_scenario_demo.cpp.s
.PHONY : apps/test_scenario_demo.s

# target to generate assembly for a file
apps/test_scenario_demo.cpp.s:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/test_scenario_demo.dir/build.make CMakeFiles/test_scenario_demo.dir/apps/test_scenario_demo.cpp.s
.PHONY : apps/test_scenario_demo.cpp.s

src/core/ECS/ComponentAccessManager.o: src/core/ECS/ComponentAccessManager.cpp.o
.PHONY : src/core/ECS/ComponentAccessManager.o

# target to build an object file
src/core/ECS/ComponentAccessManager.cpp.o:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/mechanica_imperii.dir/build.make CMakeFiles/mechanica_imperii.dir/src/core/ECS/ComponentAccessManager.cpp.o
	$(MAKE) $(MAKESILENT) -f CMakeFiles/test_scenario_demo.dir/build.make CMakeFiles/test_scenario_demo.dir/src/core/ECS/ComponentAccessManager.cpp.o
.PHONY : src/core/ECS/ComponentAccessManager.cpp.o

src/core/ECS/ComponentAccessManager.i: src/core/ECS/ComponentAccessManager.cpp.i
.PHONY : src/core/ECS/ComponentAccessManager.i

# target to preprocess a source file
src/core/ECS/ComponentAccessManager.cpp.i:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/mechanica_imperii.dir/build.make CMakeFiles/mechanica_imperii.dir/src/core/ECS/ComponentAccessManager.cpp.i
	$(MAKE) $(MAKESILENT) -f CMakeFiles/test_scenario_demo.dir/build.make CMakeFiles/test_scenario_demo.dir/src/core/ECS/ComponentAccessManager.cpp.i
.PHONY : src/core/ECS/ComponentAccessManager.cpp.i

src/core/ECS/ComponentAccessManager.s: src/core/ECS/ComponentAccessManager.cpp.s
.PHONY : src/core/ECS/ComponentAccessManager.s

# target to generate assembly for a file
src/core/ECS/ComponentAccessManager.cpp.s:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/mechanica_imperii.dir/build.make CMakeFiles/mechanica_imperii.dir/src/core/ECS/ComponentAccessManager.cpp.s
	$(MAKE) $(MAKESILENT) -f CMakeFiles/test_scenario_demo.dir/build.make CMakeFiles/test_scenario_demo.dir/src/core/ECS/ComponentAccessManager.cpp.s
.PHONY : src/core/ECS/ComponentAccessManager.cpp.s

src/core/ECS/MessageBus.o: src/core/ECS/MessageBus.cpp.o
.PHONY : src/core/ECS/MessageBus.o

# target to build an object file
src/core/ECS/MessageBus.cpp.o:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/mechanica_imperii.dir/build.make CMakeFiles/mechanica_imperii.dir/src/core/ECS/MessageBus.cpp.o
	$(MAKE) $(MAKESILENT) -f CMakeFiles/test_scenario_demo.dir/build.make CMakeFiles/test_scenario_demo.dir/src/core/ECS/MessageBus.cpp.o
.PHONY : src/core/ECS/MessageBus.cpp.o

src/core/ECS/MessageBus.i: src/core/ECS/MessageBus.cpp.i
.PHONY : src/core/ECS/MessageBus.i

# target to preprocess a source file
src/core/ECS/MessageBus.cpp.i:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/mechanica_imperii.dir/build.make CMakeFiles/mechanica_imperii.dir/src/core/ECS/MessageBus.cpp.i
	$(MAKE) $(MAKESILENT) -f CMakeFiles/test_scenario_demo.dir/build.make CMakeFiles/test_scenario_demo.dir/src/core/ECS/MessageBus.cpp.i
.PHONY : src/core/ECS/MessageBus.cpp.i

src/core/ECS/MessageBus.s: src/core/ECS/MessageBus.cpp.s
.PHONY : src/core/ECS/MessageBus.s

# target to generate assembly for a file
src/core/ECS/MessageBus.cpp.s:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/mechanica_imperii.dir/build.make CMakeFiles/mechanica_imperii.dir/src/core/ECS/MessageBus.cpp.s
	$(MAKE) $(MAKESILENT) -f CMakeFiles/test_scenario_demo.dir/build.make CMakeFiles/test_scenario_demo.dir/src/core/ECS/MessageBus.cpp.s
.PHONY : src/core/ECS/MessageBus.cpp.s

src/core/threading/ThreadedSystemManager.o: src/core/threading/ThreadedSystemManager.cpp.o
.PHONY : src/core/threading/ThreadedSystemManager.o

# target to build an object file
src/core/threading/ThreadedSystemManager.cpp.o:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/mechanica_imperii.dir/build.make CMakeFiles/mechanica_imperii.dir/src/core/threading/ThreadedSystemManager.cpp.o
.PHONY : src/core/threading/ThreadedSystemManager.cpp.o

src/core/threading/ThreadedSystemManager.i: src/core/threading/ThreadedSystemManager.cpp.i
.PHONY : src/core/threading/ThreadedSystemManager.i

# target to preprocess a source file
src/core/threading/ThreadedSystemManager.cpp.i:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/mechanica_imperii.dir/build.make CMakeFiles/mechanica_imperii.dir/src/core/threading/ThreadedSystemManager.cpp.i
.PHONY : src/core/threading/ThreadedSystemManager.cpp.i

src/core/threading/ThreadedSystemManager.s: src/core/threading/ThreadedSystemManager.cpp.s
.PHONY : src/core/threading/ThreadedSystemManager.s

# target to generate assembly for a file
src/core/threading/ThreadedSystemManager.cpp.s:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/mechanica_imperii.dir/build.make CMakeFiles/mechanica_imperii.dir/src/core/threading/ThreadedSystemManager.cpp.s
.PHONY : src/core/threading/ThreadedSystemManager.cpp.s

src/game/administration/AdministrativeComponents.o: src/game/administration/AdministrativeComponents.cpp.o
.PHONY : src/game/administration/AdministrativeComponents.o

# target to build an object file
src/game/administration/AdministrativeComponents.cpp.o:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/mechanica_imperii.dir/build.make CMakeFiles/mechanica_imperii.dir/src/game/administration/AdministrativeComponents.cpp.o
.PHONY : src/game/administration/AdministrativeComponents.cpp.o

src/game/administration/AdministrativeComponents.i: src/game/administration/AdministrativeComponents.cpp.i
.PHONY : src/game/administration/AdministrativeComponents.i

# target to preprocess a source file
src/game/administration/AdministrativeComponents.cpp.i:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/mechanica_imperii.dir/build.make CMakeFiles/mechanica_imperii.dir/src/game/administration/AdministrativeComponents.cpp.i
.PHONY : src/game/administration/AdministrativeComponents.cpp.i

src/game/administration/AdministrativeComponents.s: src/game/administration/AdministrativeComponents.cpp.s
.PHONY : src/game/administration/AdministrativeComponents.s

# target to generate assembly for a file
src/game/administration/AdministrativeComponents.cpp.s:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/mechanica_imperii.dir/build.make CMakeFiles/mechanica_imperii.dir/src/game/administration/AdministrativeComponents.cpp.s
.PHONY : src/game/administration/AdministrativeComponents.cpp.s

src/game/administration/AdministrativeOfficial.o: src/game/administration/AdministrativeOfficial.cpp.o
.PHONY : src/game/administration/AdministrativeOfficial.o

# target to build an object file
src/game/administration/AdministrativeOfficial.cpp.o:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/mechanica_imperii.dir/build.make CMakeFiles/mechanica_imperii.dir/src/game/administration/AdministrativeOfficial.cpp.o
.PHONY : src/game/administration/AdministrativeOfficial.cpp.o

src/game/administration/AdministrativeOfficial.i: src/game/administration/AdministrativeOfficial.cpp.i
.PHONY : src/game/administration/AdministrativeOfficial.i

# target to preprocess a source file
src/game/administration/AdministrativeOfficial.cpp.i:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/mechanica_imperii.dir/build.make CMakeFiles/mechanica_imperii.dir/src/game/administration/AdministrativeOfficial.cpp.i
.PHONY : src/game/administration/AdministrativeOfficial.cpp.i

src/game/administration/AdministrativeOfficial.s: src/game/administration/AdministrativeOfficial.cpp.s
.PHONY : src/game/administration/AdministrativeOfficial.s

# target to generate assembly for a file
src/game/administration/AdministrativeOfficial.cpp.s:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/mechanica_imperii.dir/build.make CMakeFiles/mechanica_imperii.dir/src/game/administration/AdministrativeOfficial.cpp.s
.PHONY : src/game/administration/AdministrativeOfficial.cpp.s

src/game/administration/AdministrativeSystem.o: src/game/administration/AdministrativeSystem.cpp.o
.PHONY : src/game/administration/AdministrativeSystem.o

# target to build an object file
src/game/administration/AdministrativeSystem.cpp.o:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/mechanica_imperii.dir/build.make CMakeFiles/mechanica_imperii.dir/src/game/administration/AdministrativeSystem.cpp.o
.PHONY : src/game/administration/AdministrativeSystem.cpp.o

src/game/administration/AdministrativeSystem.i: src/game/administration/AdministrativeSystem.cpp.i
.PHONY : src/game/administration/AdministrativeSystem.i

# target to preprocess a source file
src/game/administration/AdministrativeSystem.cpp.i:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/mechanica_imperii.dir/build.make CMakeFiles/mechanica_imperii.dir/src/game/administration/AdministrativeSystem.cpp.i
.PHONY : src/game/administration/AdministrativeSystem.cpp.i

src/game/administration/AdministrativeSystem.s: src/game/administration/AdministrativeSystem.cpp.s
.PHONY : src/game/administration/AdministrativeSystem.s

# target to generate assembly for a file
src/game/administration/AdministrativeSystem.cpp.s:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/mechanica_imperii.dir/build.make CMakeFiles/mechanica_imperii.dir/src/game/administration/AdministrativeSystem.cpp.s
.PHONY : src/game/administration/AdministrativeSystem.cpp.s

src/game/ai/AIAttentionManager.o: src/game/ai/AIAttentionManager.cpp.o
.PHONY : src/game/ai/AIAttentionManager.o

# target to build an object file
src/game/ai/AIAttentionManager.cpp.o:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/mechanica_imperii.dir/build.make CMakeFiles/mechanica_imperii.dir/src/game/ai/AIAttentionManager.cpp.o
.PHONY : src/game/ai/AIAttentionManager.cpp.o

src/game/ai/AIAttentionManager.i: src/game/ai/AIAttentionManager.cpp.i
.PHONY : src/game/ai/AIAttentionManager.i

# target to preprocess a source file
src/game/ai/AIAttentionManager.cpp.i:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/mechanica_imperii.dir/build.make CMakeFiles/mechanica_imperii.dir/src/game/ai/AIAttentionManager.cpp.i
.PHONY : src/game/ai/AIAttentionManager.cpp.i

src/game/ai/AIAttentionManager.s: src/game/ai/AIAttentionManager.cpp.s
.PHONY : src/game/ai/AIAttentionManager.s

# target to generate assembly for a file
src/game/ai/AIAttentionManager.cpp.s:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/mechanica_imperii.dir/build.make CMakeFiles/mechanica_imperii.dir/src/game/ai/AIAttentionManager.cpp.s
.PHONY : src/game/ai/AIAttentionManager.cpp.s

src/game/ai/AIDirector.o: src/game/ai/AIDirector.cpp.o
.PHONY : src/game/ai/AIDirector.o

# target to build an object file
src/game/ai/AIDirector.cpp.o:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/mechanica_imperii.dir/build.make CMakeFiles/mechanica_imperii.dir/src/game/ai/AIDirector.cpp.o
.PHONY : src/game/ai/AIDirector.cpp.o

src/game/ai/AIDirector.i: src/game/ai/AIDirector.cpp.i
.PHONY : src/game/ai/AIDirector.i

# target to preprocess a source file
src/game/ai/AIDirector.cpp.i:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/mechanica_imperii.dir/build.make CMakeFiles/mechanica_imperii.dir/src/game/ai/AIDirector.cpp.i
.PHONY : src/game/ai/AIDirector.cpp.i

src/game/ai/AIDirector.s: src/game/ai/AIDirector.cpp.s
.PHONY : src/game/ai/AIDirector.s

# target to generate assembly for a file
src/game/ai/AIDirector.cpp.s:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/mechanica_imperii.dir/build.make CMakeFiles/mechanica_imperii.dir/src/game/ai/AIDirector.cpp.s
.PHONY : src/game/ai/AIDirector.cpp.s

src/game/ai/InformationPropagationSystem.o: src/game/ai/InformationPropagationSystem.cpp.o
.PHONY : src/game/ai/InformationPropagationSystem.o

# target to build an object file
src/game/ai/InformationPropagationSystem.cpp.o:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/mechanica_imperii.dir/build.make CMakeFiles/mechanica_imperii.dir/src/game/ai/InformationPropagationSystem.cpp.o
.PHONY : src/game/ai/InformationPropagationSystem.cpp.o

src/game/ai/InformationPropagationSystem.i: src/game/ai/InformationPropagationSystem.cpp.i
.PHONY : src/game/ai/InformationPropagationSystem.i

# target to preprocess a source file
src/game/ai/InformationPropagationSystem.cpp.i:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/mechanica_imperii.dir/build.make CMakeFiles/mechanica_imperii.dir/src/game/ai/InformationPropagationSystem.cpp.i
.PHONY : src/game/ai/InformationPropagationSystem.cpp.i

src/game/ai/InformationPropagationSystem.s: src/game/ai/InformationPropagationSystem.cpp.s
.PHONY : src/game/ai/InformationPropagationSystem.s

# target to generate assembly for a file
src/game/ai/InformationPropagationSystem.cpp.s:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/mechanica_imperii.dir/build.make CMakeFiles/mechanica_imperii.dir/src/game/ai/InformationPropagationSystem.cpp.s
.PHONY : src/game/ai/InformationPropagationSystem.cpp.s

src/game/ai/NationAI.o: src/game/ai/NationAI.cpp.o
.PHONY : src/game/ai/NationAI.o

# target to build an object file
src/game/ai/NationAI.cpp.o:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/mechanica_imperii.dir/build.make CMakeFiles/mechanica_imperii.dir/src/game/ai/NationAI.cpp.o
.PHONY : src/game/ai/NationAI.cpp.o

src/game/ai/NationAI.i: src/game/ai/NationAI.cpp.i
.PHONY : src/game/ai/NationAI.i

# target to preprocess a source file
src/game/ai/NationAI.cpp.i:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/mechanica_imperii.dir/build.make CMakeFiles/mechanica_imperii.dir/src/game/ai/NationAI.cpp.i
.PHONY : src/game/ai/NationAI.cpp.i

src/game/ai/NationAI.s: src/game/ai/NationAI.cpp.s
.PHONY : src/game/ai/NationAI.s

# target to generate assembly for a file
src/game/ai/NationAI.cpp.s:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/mechanica_imperii.dir/build.make CMakeFiles/mechanica_imperii.dir/src/game/ai/NationAI.cpp.s
.PHONY : src/game/ai/NationAI.cpp.s

src/game/config/ConfigHelpers.o: src/game/config/ConfigHelpers.cpp.o
.PHONY : src/game/config/ConfigHelpers.o

# target to build an object file
src/game/config/ConfigHelpers.cpp.o:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/mechanica_imperii.dir/build.make CMakeFiles/mechanica_imperii.dir/src/game/config/ConfigHelpers.cpp.o
	$(MAKE) $(MAKESILENT) -f CMakeFiles/test_enhanced_config.dir/build.make CMakeFiles/test_enhanced_config.dir/src/game/config/ConfigHelpers.cpp.o
	$(MAKE) $(MAKESILENT) -f CMakeFiles/test_scenario_demo.dir/build.make CMakeFiles/test_scenario_demo.dir/src/game/config/ConfigHelpers.cpp.o
.PHONY : src/game/config/ConfigHelpers.cpp.o

src/game/config/ConfigHelpers.i: src/game/config/ConfigHelpers.cpp.i
.PHONY : src/game/config/ConfigHelpers.i

# target to preprocess a source file
src/game/config/ConfigHelpers.cpp.i:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/mechanica_imperii.dir/build.make CMakeFiles/mechanica_imperii.dir/src/game/config/ConfigHelpers.cpp.i
	$(MAKE) $(MAKESILENT) -f CMakeFiles/test_enhanced_config.dir/build.make CMakeFiles/test_enhanced_config.dir/src/game/config/ConfigHelpers.cpp.i
	$(MAKE) $(MAKESILENT) -f CMakeFiles/test_scenario_demo.dir/build.make CMakeFiles/test_scenario_demo.dir/src/game/config/ConfigHelpers.cpp.i
.PHONY : src/game/config/ConfigHelpers.cpp.i

src/game/config/ConfigHelpers.s: src/game/config/ConfigHelpers.cpp.s
.PHONY : src/game/config/ConfigHelpers.s

# target to generate assembly for a file
src/game/config/ConfigHelpers.cpp.s:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/mechanica_imperii.dir/build.make CMakeFiles/mechanica_imperii.dir/src/game/config/ConfigHelpers.cpp.s
	$(MAKE) $(MAKESILENT) -f CMakeFiles/test_enhanced_config.dir/build.make CMakeFiles/test_enhanced_config.dir/src/game/config/ConfigHelpers.cpp.s
	$(MAKE) $(MAKESILENT) -f CMakeFiles/test_scenario_demo.dir/build.make CMakeFiles/test_scenario_demo.dir/src/game/config/ConfigHelpers.cpp.s
.PHONY : src/game/config/ConfigHelpers.cpp.s

src/game/config/GameConfig.o: src/game/config/GameConfig.cpp.o
.PHONY : src/game/config/GameConfig.o

# target to build an object file
src/game/config/GameConfig.cpp.o:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/mechanica_imperii.dir/build.make CMakeFiles/mechanica_imperii.dir/src/game/config/GameConfig.cpp.o
	$(MAKE) $(MAKESILENT) -f CMakeFiles/test_enhanced_config.dir/build.make CMakeFiles/test_enhanced_config.dir/src/game/config/GameConfig.cpp.o
	$(MAKE) $(MAKESILENT) -f CMakeFiles/test_scenario_demo.dir/build.make CMakeFiles/test_scenario_demo.dir/src/game/config/GameConfig.cpp.o
.PHONY : src/game/config/GameConfig.cpp.o

src/game/config/GameConfig.i: src/game/config/GameConfig.cpp.i
.PHONY : src/game/config/GameConfig.i

# target to preprocess a source file
src/game/config/GameConfig.cpp.i:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/mechanica_imperii.dir/build.make CMakeFiles/mechanica_imperii.dir/src/game/config/GameConfig.cpp.i
	$(MAKE) $(MAKESILENT) -f CMakeFiles/test_enhanced_config.dir/build.make CMakeFiles/test_enhanced_config.dir/src/game/config/GameConfig.cpp.i
	$(MAKE) $(MAKESILENT) -f CMakeFiles/test_scenario_demo.dir/build.make CMakeFiles/test_scenario_demo.dir/src/game/config/GameConfig.cpp.i
.PHONY : src/game/config/GameConfig.cpp.i

src/game/config/GameConfig.s: src/game/config/GameConfig.cpp.s
.PHONY : src/game/config/GameConfig.s

# target to generate assembly for a file
src/game/config/GameConfig.cpp.s:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/mechanica_imperii.dir/build.make CMakeFiles/mechanica_imperii.dir/src/game/config/GameConfig.cpp.s
	$(MAKE) $(MAKESILENT) -f CMakeFiles/test_enhanced_config.dir/build.make CMakeFiles/test_enhanced_config.dir/src/game/config/GameConfig.cpp.s
	$(MAKE) $(MAKESILENT) -f CMakeFiles/test_scenario_demo.dir/build.make CMakeFiles/test_scenario_demo.dir/src/game/config/GameConfig.cpp.s
.PHONY : src/game/config/GameConfig.cpp.s

src/game/diplomacy/DiplomacyComponents.o: src/game/diplomacy/DiplomacyComponents.cpp.o
.PHONY : src/game/diplomacy/DiplomacyComponents.o

# target to build an object file
src/game/diplomacy/DiplomacyComponents.cpp.o:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/mechanica_imperii.dir/build.make CMakeFiles/mechanica_imperii.dir/src/game/diplomacy/DiplomacyComponents.cpp.o
.PHONY : src/game/diplomacy/DiplomacyComponents.cpp.o

src/game/diplomacy/DiplomacyComponents.i: src/game/diplomacy/DiplomacyComponents.cpp.i
.PHONY : src/game/diplomacy/DiplomacyComponents.i

# target to preprocess a source file
src/game/diplomacy/DiplomacyComponents.cpp.i:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/mechanica_imperii.dir/build.make CMakeFiles/mechanica_imperii.dir/src/game/diplomacy/DiplomacyComponents.cpp.i
.PHONY : src/game/diplomacy/DiplomacyComponents.cpp.i

src/game/diplomacy/DiplomacyComponents.s: src/game/diplomacy/DiplomacyComponents.cpp.s
.PHONY : src/game/diplomacy/DiplomacyComponents.s

# target to generate assembly for a file
src/game/diplomacy/DiplomacyComponents.cpp.s:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/mechanica_imperii.dir/build.make CMakeFiles/mechanica_imperii.dir/src/game/diplomacy/DiplomacyComponents.cpp.s
.PHONY : src/game/diplomacy/DiplomacyComponents.cpp.s

src/game/diplomacy/DiplomacySystem.o: src/game/diplomacy/DiplomacySystem.cpp.o
.PHONY : src/game/diplomacy/DiplomacySystem.o

# target to build an object file
src/game/diplomacy/DiplomacySystem.cpp.o:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/mechanica_imperii.dir/build.make CMakeFiles/mechanica_imperii.dir/src/game/diplomacy/DiplomacySystem.cpp.o
.PHONY : src/game/diplomacy/DiplomacySystem.cpp.o

src/game/diplomacy/DiplomacySystem.i: src/game/diplomacy/DiplomacySystem.cpp.i
.PHONY : src/game/diplomacy/DiplomacySystem.i

# target to preprocess a source file
src/game/diplomacy/DiplomacySystem.cpp.i:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/mechanica_imperii.dir/build.make CMakeFiles/mechanica_imperii.dir/src/game/diplomacy/DiplomacySystem.cpp.i
.PHONY : src/game/diplomacy/DiplomacySystem.cpp.i

src/game/diplomacy/DiplomacySystem.s: src/game/diplomacy/DiplomacySystem.cpp.s
.PHONY : src/game/diplomacy/DiplomacySystem.s

# target to generate assembly for a file
src/game/diplomacy/DiplomacySystem.cpp.s:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/mechanica_imperii.dir/build.make CMakeFiles/mechanica_imperii.dir/src/game/diplomacy/DiplomacySystem.cpp.s
.PHONY : src/game/diplomacy/DiplomacySystem.cpp.s

src/game/diplomacy/DiplomacySystemSerialization.o: src/game/diplomacy/DiplomacySystemSerialization.cpp.o
.PHONY : src/game/diplomacy/DiplomacySystemSerialization.o

# target to build an object file
src/game/diplomacy/DiplomacySystemSerialization.cpp.o:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/mechanica_imperii.dir/build.make CMakeFiles/mechanica_imperii.dir/src/game/diplomacy/DiplomacySystemSerialization.cpp.o
.PHONY : src/game/diplomacy/DiplomacySystemSerialization.cpp.o

src/game/diplomacy/DiplomacySystemSerialization.i: src/game/diplomacy/DiplomacySystemSerialization.cpp.i
.PHONY : src/game/diplomacy/DiplomacySystemSerialization.i

# target to preprocess a source file
src/game/diplomacy/DiplomacySystemSerialization.cpp.i:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/mechanica_imperii.dir/build.make CMakeFiles/mechanica_imperii.dir/src/game/diplomacy/DiplomacySystemSerialization.cpp.i
.PHONY : src/game/diplomacy/DiplomacySystemSerialization.cpp.i

src/game/diplomacy/DiplomacySystemSerialization.s: src/game/diplomacy/DiplomacySystemSerialization.cpp.s
.PHONY : src/game/diplomacy/DiplomacySystemSerialization.s

# target to generate assembly for a file
src/game/diplomacy/DiplomacySystemSerialization.cpp.s:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/mechanica_imperii.dir/build.make CMakeFiles/mechanica_imperii.dir/src/game/diplomacy/DiplomacySystemSerialization.cpp.s
.PHONY : src/game/diplomacy/DiplomacySystemSerialization.cpp.s

src/game/economy/EconomicComponents.o: src/game/economy/EconomicComponents.cpp.o
.PHONY : src/game/economy/EconomicComponents.o

# target to build an object file
src/game/economy/EconomicComponents.cpp.o:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/mechanica_imperii.dir/build.make CMakeFiles/mechanica_imperii.dir/src/game/economy/EconomicComponents.cpp.o
.PHONY : src/game/economy/EconomicComponents.cpp.o

src/game/economy/EconomicComponents.i: src/game/economy/EconomicComponents.cpp.i
.PHONY : src/game/economy/EconomicComponents.i

# target to preprocess a source file
src/game/economy/EconomicComponents.cpp.i:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/mechanica_imperii.dir/build.make CMakeFiles/mechanica_imperii.dir/src/game/economy/EconomicComponents.cpp.i
.PHONY : src/game/economy/EconomicComponents.cpp.i

src/game/economy/EconomicComponents.s: src/game/economy/EconomicComponents.cpp.s
.PHONY : src/game/economy/EconomicComponents.s

# target to generate assembly for a file
src/game/economy/EconomicComponents.cpp.s:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/mechanica_imperii.dir/build.make CMakeFiles/mechanica_imperii.dir/src/game/economy/EconomicComponents.cpp.s
.PHONY : src/game/economy/EconomicComponents.cpp.s

src/game/economy/EconomicPopulationBridge.o: src/game/economy/EconomicPopulationBridge.cpp.o
.PHONY : src/game/economy/EconomicPopulationBridge.o

# target to build an object file
src/game/economy/EconomicPopulationBridge.cpp.o:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/mechanica_imperii.dir/build.make CMakeFiles/mechanica_imperii.dir/src/game/economy/EconomicPopulationBridge.cpp.o
.PHONY : src/game/economy/EconomicPopulationBridge.cpp.o

src/game/economy/EconomicPopulationBridge.i: src/game/economy/EconomicPopulationBridge.cpp.i
.PHONY : src/game/economy/EconomicPopulationBridge.i

# target to preprocess a source file
src/game/economy/EconomicPopulationBridge.cpp.i:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/mechanica_imperii.dir/build.make CMakeFiles/mechanica_imperii.dir/src/game/economy/EconomicPopulationBridge.cpp.i
.PHONY : src/game/economy/EconomicPopulationBridge.cpp.i

src/game/economy/EconomicPopulationBridge.s: src/game/economy/EconomicPopulationBridge.cpp.s
.PHONY : src/game/economy/EconomicPopulationBridge.s

# target to generate assembly for a file
src/game/economy/EconomicPopulationBridge.cpp.s:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/mechanica_imperii.dir/build.make CMakeFiles/mechanica_imperii.dir/src/game/economy/EconomicPopulationBridge.cpp.s
.PHONY : src/game/economy/EconomicPopulationBridge.cpp.s

src/game/economy/EconomicPopulationBridgeSerialization.o: src/game/economy/EconomicPopulationBridgeSerialization.cpp.o
.PHONY : src/game/economy/EconomicPopulationBridgeSerialization.o

# target to build an object file
src/game/economy/EconomicPopulationBridgeSerialization.cpp.o:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/mechanica_imperii.dir/build.make CMakeFiles/mechanica_imperii.dir/src/game/economy/EconomicPopulationBridgeSerialization.cpp.o
.PHONY : src/game/economy/EconomicPopulationBridgeSerialization.cpp.o

src/game/economy/EconomicPopulationBridgeSerialization.i: src/game/economy/EconomicPopulationBridgeSerialization.cpp.i
.PHONY : src/game/economy/EconomicPopulationBridgeSerialization.i

# target to preprocess a source file
src/game/economy/EconomicPopulationBridgeSerialization.cpp.i:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/mechanica_imperii.dir/build.make CMakeFiles/mechanica_imperii.dir/src/game/economy/EconomicPopulationBridgeSerialization.cpp.i
.PHONY : src/game/economy/EconomicPopulationBridgeSerialization.cpp.i

src/game/economy/EconomicPopulationBridgeSerialization.s: src/game/economy/EconomicPopulationBridgeSerialization.cpp.s
.PHONY : src/game/economy/EconomicPopulationBridgeSerialization.s

# target to generate assembly for a file
src/game/economy/EconomicPopulationBridgeSerialization.cpp.s:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/mechanica_imperii.dir/build.make CMakeFiles/mechanica_imperii.dir/src/game/economy/EconomicPopulationBridgeSerialization.cpp.s
.PHONY : src/game/economy/EconomicPopulationBridgeSerialization.cpp.s

src/game/economy/EconomicSystem.o: src/game/economy/EconomicSystem.cpp.o
.PHONY : src/game/economy/EconomicSystem.o

# target to build an object file
src/game/economy/EconomicSystem.cpp.o:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/mechanica_imperii.dir/build.make CMakeFiles/mechanica_imperii.dir/src/game/economy/EconomicSystem.cpp.o
.PHONY : src/game/economy/EconomicSystem.cpp.o

src/game/economy/EconomicSystem.i: src/game/economy/EconomicSystem.cpp.i
.PHONY : src/game/economy/EconomicSystem.i

# target to preprocess a source file
src/game/economy/EconomicSystem.cpp.i:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/mechanica_imperii.dir/build.make CMakeFiles/mechanica_imperii.dir/src/game/economy/EconomicSystem.cpp.i
.PHONY : src/game/economy/EconomicSystem.cpp.i

src/game/economy/EconomicSystem.s: src/game/economy/EconomicSystem.cpp.s
.PHONY : src/game/economy/EconomicSystem.s

# target to generate assembly for a file
src/game/economy/EconomicSystem.cpp.s:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/mechanica_imperii.dir/build.make CMakeFiles/mechanica_imperii.dir/src/game/economy/EconomicSystem.cpp.s
.PHONY : src/game/economy/EconomicSystem.cpp.s

src/game/military/MilitaryComponents.o: src/game/military/MilitaryComponents.cpp.o
.PHONY : src/game/military/MilitaryComponents.o

# target to build an object file
src/game/military/MilitaryComponents.cpp.o:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/mechanica_imperii.dir/build.make CMakeFiles/mechanica_imperii.dir/src/game/military/MilitaryComponents.cpp.o
.PHONY : src/game/military/MilitaryComponents.cpp.o

src/game/military/MilitaryComponents.i: src/game/military/MilitaryComponents.cpp.i
.PHONY : src/game/military/MilitaryComponents.i

# target to preprocess a source file
src/game/military/MilitaryComponents.cpp.i:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/mechanica_imperii.dir/build.make CMakeFiles/mechanica_imperii.dir/src/game/military/MilitaryComponents.cpp.i
.PHONY : src/game/military/MilitaryComponents.cpp.i

src/game/military/MilitaryComponents.s: src/game/military/MilitaryComponents.cpp.s
.PHONY : src/game/military/MilitaryComponents.s

# target to generate assembly for a file
src/game/military/MilitaryComponents.cpp.s:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/mechanica_imperii.dir/build.make CMakeFiles/mechanica_imperii.dir/src/game/military/MilitaryComponents.cpp.s
.PHONY : src/game/military/MilitaryComponents.cpp.s

src/game/military/MilitaryDatabase_Utils.o: src/game/military/MilitaryDatabase_Utils.cpp.o
.PHONY : src/game/military/MilitaryDatabase_Utils.o

# target to build an object file
src/game/military/MilitaryDatabase_Utils.cpp.o:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/mechanica_imperii.dir/build.make CMakeFiles/mechanica_imperii.dir/src/game/military/MilitaryDatabase_Utils.cpp.o
.PHONY : src/game/military/MilitaryDatabase_Utils.cpp.o

src/game/military/MilitaryDatabase_Utils.i: src/game/military/MilitaryDatabase_Utils.cpp.i
.PHONY : src/game/military/MilitaryDatabase_Utils.i

# target to preprocess a source file
src/game/military/MilitaryDatabase_Utils.cpp.i:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/mechanica_imperii.dir/build.make CMakeFiles/mechanica_imperii.dir/src/game/military/MilitaryDatabase_Utils.cpp.i
.PHONY : src/game/military/MilitaryDatabase_Utils.cpp.i

src/game/military/MilitaryDatabase_Utils.s: src/game/military/MilitaryDatabase_Utils.cpp.s
.PHONY : src/game/military/MilitaryDatabase_Utils.s

# target to generate assembly for a file
src/game/military/MilitaryDatabase_Utils.cpp.s:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/mechanica_imperii.dir/build.make CMakeFiles/mechanica_imperii.dir/src/game/military/MilitaryDatabase_Utils.cpp.s
.PHONY : src/game/military/MilitaryDatabase_Utils.cpp.s

src/game/military/MilitaryRecruitmentSystem.o: src/game/military/MilitaryRecruitmentSystem.cpp.o
.PHONY : src/game/military/MilitaryRecruitmentSystem.o

# target to build an object file
src/game/military/MilitaryRecruitmentSystem.cpp.o:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/mechanica_imperii.dir/build.make CMakeFiles/mechanica_imperii.dir/src/game/military/MilitaryRecruitmentSystem.cpp.o
.PHONY : src/game/military/MilitaryRecruitmentSystem.cpp.o

src/game/military/MilitaryRecruitmentSystem.i: src/game/military/MilitaryRecruitmentSystem.cpp.i
.PHONY : src/game/military/MilitaryRecruitmentSystem.i

# target to preprocess a source file
src/game/military/MilitaryRecruitmentSystem.cpp.i:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/mechanica_imperii.dir/build.make CMakeFiles/mechanica_imperii.dir/src/game/military/MilitaryRecruitmentSystem.cpp.i
.PHONY : src/game/military/MilitaryRecruitmentSystem.cpp.i

src/game/military/MilitaryRecruitmentSystem.s: src/game/military/MilitaryRecruitmentSystem.cpp.s
.PHONY : src/game/military/MilitaryRecruitmentSystem.s

# target to generate assembly for a file
src/game/military/MilitaryRecruitmentSystem.cpp.s:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/mechanica_imperii.dir/build.make CMakeFiles/mechanica_imperii.dir/src/game/military/MilitaryRecruitmentSystem.cpp.s
.PHONY : src/game/military/MilitaryRecruitmentSystem.cpp.s

src/game/military/MilitarySystem.o: src/game/military/MilitarySystem.cpp.o
.PHONY : src/game/military/MilitarySystem.o

# target to build an object file
src/game/military/MilitarySystem.cpp.o:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/mechanica_imperii.dir/build.make CMakeFiles/mechanica_imperii.dir/src/game/military/MilitarySystem.cpp.o
.PHONY : src/game/military/MilitarySystem.cpp.o

src/game/military/MilitarySystem.i: src/game/military/MilitarySystem.cpp.i
.PHONY : src/game/military/MilitarySystem.i

# target to preprocess a source file
src/game/military/MilitarySystem.cpp.i:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/mechanica_imperii.dir/build.make CMakeFiles/mechanica_imperii.dir/src/game/military/MilitarySystem.cpp.i
.PHONY : src/game/military/MilitarySystem.cpp.i

src/game/military/MilitarySystem.s: src/game/military/MilitarySystem.cpp.s
.PHONY : src/game/military/MilitarySystem.s

# target to generate assembly for a file
src/game/military/MilitarySystem.cpp.s:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/mechanica_imperii.dir/build.make CMakeFiles/mechanica_imperii.dir/src/game/military/MilitarySystem.cpp.s
.PHONY : src/game/military/MilitarySystem.cpp.s

src/game/population/PopulationAggregator.o: src/game/population/PopulationAggregator.cpp.o
.PHONY : src/game/population/PopulationAggregator.o

# target to build an object file
src/game/population/PopulationAggregator.cpp.o:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/mechanica_imperii.dir/build.make CMakeFiles/mechanica_imperii.dir/src/game/population/PopulationAggregator.cpp.o
.PHONY : src/game/population/PopulationAggregator.cpp.o

src/game/population/PopulationAggregator.i: src/game/population/PopulationAggregator.cpp.i
.PHONY : src/game/population/PopulationAggregator.i

# target to preprocess a source file
src/game/population/PopulationAggregator.cpp.i:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/mechanica_imperii.dir/build.make CMakeFiles/mechanica_imperii.dir/src/game/population/PopulationAggregator.cpp.i
.PHONY : src/game/population/PopulationAggregator.cpp.i

src/game/population/PopulationAggregator.s: src/game/population/PopulationAggregator.cpp.s
.PHONY : src/game/population/PopulationAggregator.s

# target to generate assembly for a file
src/game/population/PopulationAggregator.cpp.s:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/mechanica_imperii.dir/build.make CMakeFiles/mechanica_imperii.dir/src/game/population/PopulationAggregator.cpp.s
.PHONY : src/game/population/PopulationAggregator.cpp.s

src/game/population/PopulationComponents.o: src/game/population/PopulationComponents.cpp.o
.PHONY : src/game/population/PopulationComponents.o

# target to build an object file
src/game/population/PopulationComponents.cpp.o:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/mechanica_imperii.dir/build.make CMakeFiles/mechanica_imperii.dir/src/game/population/PopulationComponents.cpp.o
.PHONY : src/game/population/PopulationComponents.cpp.o

src/game/population/PopulationComponents.i: src/game/population/PopulationComponents.cpp.i
.PHONY : src/game/population/PopulationComponents.i

# target to preprocess a source file
src/game/population/PopulationComponents.cpp.i:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/mechanica_imperii.dir/build.make CMakeFiles/mechanica_imperii.dir/src/game/population/PopulationComponents.cpp.i
.PHONY : src/game/population/PopulationComponents.cpp.i

src/game/population/PopulationComponents.s: src/game/population/PopulationComponents.cpp.s
.PHONY : src/game/population/PopulationComponents.s

# target to generate assembly for a file
src/game/population/PopulationComponents.cpp.s:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/mechanica_imperii.dir/build.make CMakeFiles/mechanica_imperii.dir/src/game/population/PopulationComponents.cpp.s
.PHONY : src/game/population/PopulationComponents.cpp.s

src/game/population/PopulationEventProcessor.o: src/game/population/PopulationEventProcessor.cpp.o
.PHONY : src/game/population/PopulationEventProcessor.o

# target to build an object file
src/game/population/PopulationEventProcessor.cpp.o:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/mechanica_imperii.dir/build.make CMakeFiles/mechanica_imperii.dir/src/game/population/PopulationEventProcessor.cpp.o
.PHONY : src/game/population/PopulationEventProcessor.cpp.o

src/game/population/PopulationEventProcessor.i: src/game/population/PopulationEventProcessor.cpp.i
.PHONY : src/game/population/PopulationEventProcessor.i

# target to preprocess a source file
src/game/population/PopulationEventProcessor.cpp.i:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/mechanica_imperii.dir/build.make CMakeFiles/mechanica_imperii.dir/src/game/population/PopulationEventProcessor.cpp.i
.PHONY : src/game/population/PopulationEventProcessor.cpp.i

src/game/population/PopulationEventProcessor.s: src/game/population/PopulationEventProcessor.cpp.s
.PHONY : src/game/population/PopulationEventProcessor.s

# target to generate assembly for a file
src/game/population/PopulationEventProcessor.cpp.s:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/mechanica_imperii.dir/build.make CMakeFiles/mechanica_imperii.dir/src/game/population/PopulationEventProcessor.cpp.s
.PHONY : src/game/population/PopulationEventProcessor.cpp.s

src/game/population/PopulationFactory.o: src/game/population/PopulationFactory.cpp.o
.PHONY : src/game/population/PopulationFactory.o

# target to build an object file
src/game/population/PopulationFactory.cpp.o:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/mechanica_imperii.dir/build.make CMakeFiles/mechanica_imperii.dir/src/game/population/PopulationFactory.cpp.o
.PHONY : src/game/population/PopulationFactory.cpp.o

src/game/population/PopulationFactory.i: src/game/population/PopulationFactory.cpp.i
.PHONY : src/game/population/PopulationFactory.i

# target to preprocess a source file
src/game/population/PopulationFactory.cpp.i:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/mechanica_imperii.dir/build.make CMakeFiles/mechanica_imperii.dir/src/game/population/PopulationFactory.cpp.i
.PHONY : src/game/population/PopulationFactory.cpp.i

src/game/population/PopulationFactory.s: src/game/population/PopulationFactory.cpp.s
.PHONY : src/game/population/PopulationFactory.s

# target to generate assembly for a file
src/game/population/PopulationFactory.cpp.s:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/mechanica_imperii.dir/build.make CMakeFiles/mechanica_imperii.dir/src/game/population/PopulationFactory.cpp.s
.PHONY : src/game/population/PopulationFactory.cpp.s

src/game/population/PopulationSystem.o: src/game/population/PopulationSystem.cpp.o
.PHONY : src/game/population/PopulationSystem.o

# target to build an object file
src/game/population/PopulationSystem.cpp.o:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/mechanica_imperii.dir/build.make CMakeFiles/mechanica_imperii.dir/src/game/population/PopulationSystem.cpp.o
.PHONY : src/game/population/PopulationSystem.cpp.o

src/game/population/PopulationSystem.i: src/game/population/PopulationSystem.cpp.i
.PHONY : src/game/population/PopulationSystem.i

# target to preprocess a source file
src/game/population/PopulationSystem.cpp.i:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/mechanica_imperii.dir/build.make CMakeFiles/mechanica_imperii.dir/src/game/population/PopulationSystem.cpp.i
.PHONY : src/game/population/PopulationSystem.cpp.i

src/game/population/PopulationSystem.s: src/game/population/PopulationSystem.cpp.s
.PHONY : src/game/population/PopulationSystem.s

# target to generate assembly for a file
src/game/population/PopulationSystem.cpp.s:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/mechanica_imperii.dir/build.make CMakeFiles/mechanica_imperii.dir/src/game/population/PopulationSystem.cpp.s
.PHONY : src/game/population/PopulationSystem.cpp.s

src/game/population/PopulationUtils.o: src/game/population/PopulationUtils.cpp.o
.PHONY : src/game/population/PopulationUtils.o

# target to build an object file
src/game/population/PopulationUtils.cpp.o:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/mechanica_imperii.dir/build.make CMakeFiles/mechanica_imperii.dir/src/game/population/PopulationUtils.cpp.o
.PHONY : src/game/population/PopulationUtils.cpp.o

src/game/population/PopulationUtils.i: src/game/population/PopulationUtils.cpp.i
.PHONY : src/game/population/PopulationUtils.i

# target to preprocess a source file
src/game/population/PopulationUtils.cpp.i:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/mechanica_imperii.dir/build.make CMakeFiles/mechanica_imperii.dir/src/game/population/PopulationUtils.cpp.i
.PHONY : src/game/population/PopulationUtils.cpp.i

src/game/population/PopulationUtils.s: src/game/population/PopulationUtils.cpp.s
.PHONY : src/game/population/PopulationUtils.s

# target to generate assembly for a file
src/game/population/PopulationUtils.cpp.s:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/mechanica_imperii.dir/build.make CMakeFiles/mechanica_imperii.dir/src/game/population/PopulationUtils.cpp.s
.PHONY : src/game/population/PopulationUtils.cpp.s

src/game/realm/RealmComponents.o: src/game/realm/RealmComponents.cpp.o
.PHONY : src/game/realm/RealmComponents.o

# target to build an object file
src/game/realm/RealmComponents.cpp.o:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/mechanica_imperii.dir/build.make CMakeFiles/mechanica_imperii.dir/src/game/realm/RealmComponents.cpp.o
.PHONY : src/game/realm/RealmComponents.cpp.o

src/game/realm/RealmComponents.i: src/game/realm/RealmComponents.cpp.i
.PHONY : src/game/realm/RealmComponents.i

# target to preprocess a source file
src/game/realm/RealmComponents.cpp.i:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/mechanica_imperii.dir/build.make CMakeFiles/mechanica_imperii.dir/src/game/realm/RealmComponents.cpp.i
.PHONY : src/game/realm/RealmComponents.cpp.i

src/game/realm/RealmComponents.s: src/game/realm/RealmComponents.cpp.s
.PHONY : src/game/realm/RealmComponents.s

# target to generate assembly for a file
src/game/realm/RealmComponents.cpp.s:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/mechanica_imperii.dir/build.make CMakeFiles/mechanica_imperii.dir/src/game/realm/RealmComponents.cpp.s
.PHONY : src/game/realm/RealmComponents.cpp.s

src/game/realm/RealmManager.o: src/game/realm/RealmManager.cpp.o
.PHONY : src/game/realm/RealmManager.o

# target to build an object file
src/game/realm/RealmManager.cpp.o:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/mechanica_imperii.dir/build.make CMakeFiles/mechanica_imperii.dir/src/game/realm/RealmManager.cpp.o
.PHONY : src/game/realm/RealmManager.cpp.o

src/game/realm/RealmManager.i: src/game/realm/RealmManager.cpp.i
.PHONY : src/game/realm/RealmManager.i

# target to preprocess a source file
src/game/realm/RealmManager.cpp.i:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/mechanica_imperii.dir/build.make CMakeFiles/mechanica_imperii.dir/src/game/realm/RealmManager.cpp.i
.PHONY : src/game/realm/RealmManager.cpp.i

src/game/realm/RealmManager.s: src/game/realm/RealmManager.cpp.s
.PHONY : src/game/realm/RealmManager.s

# target to generate assembly for a file
src/game/realm/RealmManager.cpp.s:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/mechanica_imperii.dir/build.make CMakeFiles/mechanica_imperii.dir/src/game/realm/RealmManager.cpp.s
.PHONY : src/game/realm/RealmManager.cpp.s

src/game/scenario/ScenarioSystem.o: src/game/scenario/ScenarioSystem.cpp.o
.PHONY : src/game/scenario/ScenarioSystem.o

# target to build an object file
src/game/scenario/ScenarioSystem.cpp.o:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/mechanica_imperii.dir/build.make CMakeFiles/mechanica_imperii.dir/src/game/scenario/ScenarioSystem.cpp.o
	$(MAKE) $(MAKESILENT) -f CMakeFiles/test_scenario_demo.dir/build.make CMakeFiles/test_scenario_demo.dir/src/game/scenario/ScenarioSystem.cpp.o
.PHONY : src/game/scenario/ScenarioSystem.cpp.o

src/game/scenario/ScenarioSystem.i: src/game/scenario/ScenarioSystem.cpp.i
.PHONY : src/game/scenario/ScenarioSystem.i

# target to preprocess a source file
src/game/scenario/ScenarioSystem.cpp.i:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/mechanica_imperii.dir/build.make CMakeFiles/mechanica_imperii.dir/src/game/scenario/ScenarioSystem.cpp.i
	$(MAKE) $(MAKESILENT) -f CMakeFiles/test_scenario_demo.dir/build.make CMakeFiles/test_scenario_demo.dir/src/game/scenario/ScenarioSystem.cpp.i
.PHONY : src/game/scenario/ScenarioSystem.cpp.i

src/game/scenario/ScenarioSystem.s: src/game/scenario/ScenarioSystem.cpp.s
.PHONY : src/game/scenario/ScenarioSystem.s

# target to generate assembly for a file
src/game/scenario/ScenarioSystem.cpp.s:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/mechanica_imperii.dir/build.make CMakeFiles/mechanica_imperii.dir/src/game/scenario/ScenarioSystem.cpp.s
	$(MAKE) $(MAKESILENT) -f CMakeFiles/test_scenario_demo.dir/build.make CMakeFiles/test_scenario_demo.dir/src/game/scenario/ScenarioSystem.cpp.s
.PHONY : src/game/scenario/ScenarioSystem.cpp.s

src/game/technology/TechnologySystem.o: src/game/technology/TechnologySystem.cpp.o
.PHONY : src/game/technology/TechnologySystem.o

# target to build an object file
src/game/technology/TechnologySystem.cpp.o:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/mechanica_imperii.dir/build.make CMakeFiles/mechanica_imperii.dir/src/game/technology/TechnologySystem.cpp.o
.PHONY : src/game/technology/TechnologySystem.cpp.o

src/game/technology/TechnologySystem.i: src/game/technology/TechnologySystem.cpp.i
.PHONY : src/game/technology/TechnologySystem.i

# target to preprocess a source file
src/game/technology/TechnologySystem.cpp.i:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/mechanica_imperii.dir/build.make CMakeFiles/mechanica_imperii.dir/src/game/technology/TechnologySystem.cpp.i
.PHONY : src/game/technology/TechnologySystem.cpp.i

src/game/technology/TechnologySystem.s: src/game/technology/TechnologySystem.cpp.s
.PHONY : src/game/technology/TechnologySystem.s

# target to generate assembly for a file
src/game/technology/TechnologySystem.cpp.s:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/mechanica_imperii.dir/build.make CMakeFiles/mechanica_imperii.dir/src/game/technology/TechnologySystem.cpp.s
.PHONY : src/game/technology/TechnologySystem.cpp.s

src/game/technology/TechnologyUtils.o: src/game/technology/TechnologyUtils.cpp.o
.PHONY : src/game/technology/TechnologyUtils.o

# target to build an object file
src/game/technology/TechnologyUtils.cpp.o:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/mechanica_imperii.dir/build.make CMakeFiles/mechanica_imperii.dir/src/game/technology/TechnologyUtils.cpp.o
.PHONY : src/game/technology/TechnologyUtils.cpp.o

src/game/technology/TechnologyUtils.i: src/game/technology/TechnologyUtils.cpp.i
.PHONY : src/game/technology/TechnologyUtils.i

# target to preprocess a source file
src/game/technology/TechnologyUtils.cpp.i:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/mechanica_imperii.dir/build.make CMakeFiles/mechanica_imperii.dir/src/game/technology/TechnologyUtils.cpp.i
.PHONY : src/game/technology/TechnologyUtils.cpp.i

src/game/technology/TechnologyUtils.s: src/game/technology/TechnologyUtils.cpp.s
.PHONY : src/game/technology/TechnologyUtils.s

# target to generate assembly for a file
src/game/technology/TechnologyUtils.cpp.s:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/mechanica_imperii.dir/build.make CMakeFiles/mechanica_imperii.dir/src/game/technology/TechnologyUtils.cpp.s
.PHONY : src/game/technology/TechnologyUtils.cpp.s

src/game/time/TimeComponents.o: src/game/time/TimeComponents.cpp.o
.PHONY : src/game/time/TimeComponents.o

# target to build an object file
src/game/time/TimeComponents.cpp.o:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/mechanica_imperii.dir/build.make CMakeFiles/mechanica_imperii.dir/src/game/time/TimeComponents.cpp.o
.PHONY : src/game/time/TimeComponents.cpp.o

src/game/time/TimeComponents.i: src/game/time/TimeComponents.cpp.i
.PHONY : src/game/time/TimeComponents.i

# target to preprocess a source file
src/game/time/TimeComponents.cpp.i:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/mechanica_imperii.dir/build.make CMakeFiles/mechanica_imperii.dir/src/game/time/TimeComponents.cpp.i
.PHONY : src/game/time/TimeComponents.cpp.i

src/game/time/TimeComponents.s: src/game/time/TimeComponents.cpp.s
.PHONY : src/game/time/TimeComponents.s

# target to generate assembly for a file
src/game/time/TimeComponents.cpp.s:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/mechanica_imperii.dir/build.make CMakeFiles/mechanica_imperii.dir/src/game/time/TimeComponents.cpp.s
.PHONY : src/game/time/TimeComponents.cpp.s

src/game/time/TimeManagementSystem.o: src/game/time/TimeManagementSystem.cpp.o
.PHONY : src/game/time/TimeManagementSystem.o

# target to build an object file
src/game/time/TimeManagementSystem.cpp.o:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/mechanica_imperii.dir/build.make CMakeFiles/mechanica_imperii.dir/src/game/time/TimeManagementSystem.cpp.o
.PHONY : src/game/time/TimeManagementSystem.cpp.o

src/game/time/TimeManagementSystem.i: src/game/time/TimeManagementSystem.cpp.i
.PHONY : src/game/time/TimeManagementSystem.i

# target to preprocess a source file
src/game/time/TimeManagementSystem.cpp.i:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/mechanica_imperii.dir/build.make CMakeFiles/mechanica_imperii.dir/src/game/time/TimeManagementSystem.cpp.i
.PHONY : src/game/time/TimeManagementSystem.cpp.i

src/game/time/TimeManagementSystem.s: src/game/time/TimeManagementSystem.cpp.s
.PHONY : src/game/time/TimeManagementSystem.s

# target to generate assembly for a file
src/game/time/TimeManagementSystem.cpp.s:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/mechanica_imperii.dir/build.make CMakeFiles/mechanica_imperii.dir/src/game/time/TimeManagementSystem.cpp.s
.PHONY : src/game/time/TimeManagementSystem.cpp.s

src/ui/AdministrativeUI.o: src/ui/AdministrativeUI.cpp.o
.PHONY : src/ui/AdministrativeUI.o

# target to build an object file
src/ui/AdministrativeUI.cpp.o:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/mechanica_imperii.dir/build.make CMakeFiles/mechanica_imperii.dir/src/ui/AdministrativeUI.cpp.o
.PHONY : src/ui/AdministrativeUI.cpp.o

src/ui/AdministrativeUI.i: src/ui/AdministrativeUI.cpp.i
.PHONY : src/ui/AdministrativeUI.i

# target to preprocess a source file
src/ui/AdministrativeUI.cpp.i:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/mechanica_imperii.dir/build.make CMakeFiles/mechanica_imperii.dir/src/ui/AdministrativeUI.cpp.i
.PHONY : src/ui/AdministrativeUI.cpp.i

src/ui/AdministrativeUI.s: src/ui/AdministrativeUI.cpp.s
.PHONY : src/ui/AdministrativeUI.s

# target to generate assembly for a file
src/ui/AdministrativeUI.cpp.s:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/mechanica_imperii.dir/build.make CMakeFiles/mechanica_imperii.dir/src/ui/AdministrativeUI.cpp.s
.PHONY : src/ui/AdministrativeUI.cpp.s

src/ui/MainMenuUI.o: src/ui/MainMenuUI.cpp.o
.PHONY : src/ui/MainMenuUI.o

# target to build an object file
src/ui/MainMenuUI.cpp.o:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/mechanica_imperii.dir/build.make CMakeFiles/mechanica_imperii.dir/src/ui/MainMenuUI.cpp.o
.PHONY : src/ui/MainMenuUI.cpp.o

src/ui/MainMenuUI.i: src/ui/MainMenuUI.cpp.i
.PHONY : src/ui/MainMenuUI.i

# target to preprocess a source file
src/ui/MainMenuUI.cpp.i:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/mechanica_imperii.dir/build.make CMakeFiles/mechanica_imperii.dir/src/ui/MainMenuUI.cpp.i
.PHONY : src/ui/MainMenuUI.cpp.i

src/ui/MainMenuUI.s: src/ui/MainMenuUI.cpp.s
.PHONY : src/ui/MainMenuUI.s

# target to generate assembly for a file
src/ui/MainMenuUI.cpp.s:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/mechanica_imperii.dir/build.make CMakeFiles/mechanica_imperii.dir/src/ui/MainMenuUI.cpp.s
.PHONY : src/ui/MainMenuUI.cpp.s

src/ui/PerformanceWindow.o: src/ui/PerformanceWindow.cpp.o
.PHONY : src/ui/PerformanceWindow.o

# target to build an object file
src/ui/PerformanceWindow.cpp.o:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/mechanica_imperii.dir/build.make CMakeFiles/mechanica_imperii.dir/src/ui/PerformanceWindow.cpp.o
.PHONY : src/ui/PerformanceWindow.cpp.o

src/ui/PerformanceWindow.i: src/ui/PerformanceWindow.cpp.i
.PHONY : src/ui/PerformanceWindow.i

# target to preprocess a source file
src/ui/PerformanceWindow.cpp.i:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/mechanica_imperii.dir/build.make CMakeFiles/mechanica_imperii.dir/src/ui/PerformanceWindow.cpp.i
.PHONY : src/ui/PerformanceWindow.cpp.i

src/ui/PerformanceWindow.s: src/ui/PerformanceWindow.cpp.s
.PHONY : src/ui/PerformanceWindow.s

# target to generate assembly for a file
src/ui/PerformanceWindow.cpp.s:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/mechanica_imperii.dir/build.make CMakeFiles/mechanica_imperii.dir/src/ui/PerformanceWindow.cpp.s
.PHONY : src/ui/PerformanceWindow.cpp.s

src/ui/PopulationInfoWindow.o: src/ui/PopulationInfoWindow.cpp.o
.PHONY : src/ui/PopulationInfoWindow.o

# target to build an object file
src/ui/PopulationInfoWindow.cpp.o:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/mechanica_imperii.dir/build.make CMakeFiles/mechanica_imperii.dir/src/ui/PopulationInfoWindow.cpp.o
.PHONY : src/ui/PopulationInfoWindow.cpp.o

src/ui/PopulationInfoWindow.i: src/ui/PopulationInfoWindow.cpp.i
.PHONY : src/ui/PopulationInfoWindow.i

# target to preprocess a source file
src/ui/PopulationInfoWindow.cpp.i:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/mechanica_imperii.dir/build.make CMakeFiles/mechanica_imperii.dir/src/ui/PopulationInfoWindow.cpp.i
.PHONY : src/ui/PopulationInfoWindow.cpp.i

src/ui/PopulationInfoWindow.s: src/ui/PopulationInfoWindow.cpp.s
.PHONY : src/ui/PopulationInfoWindow.s

# target to generate assembly for a file
src/ui/PopulationInfoWindow.cpp.s:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/mechanica_imperii.dir/build.make CMakeFiles/mechanica_imperii.dir/src/ui/PopulationInfoWindow.cpp.s
.PHONY : src/ui/PopulationInfoWindow.cpp.s

src/ui/SimpleProvincePanel.o: src/ui/SimpleProvincePanel.cpp.o
.PHONY : src/ui/SimpleProvincePanel.o

# target to build an object file
src/ui/SimpleProvincePanel.cpp.o:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/mechanica_imperii.dir/build.make CMakeFiles/mechanica_imperii.dir/src/ui/SimpleProvincePanel.cpp.o
.PHONY : src/ui/SimpleProvincePanel.cpp.o

src/ui/SimpleProvincePanel.i: src/ui/SimpleProvincePanel.cpp.i
.PHONY : src/ui/SimpleProvincePanel.i

# target to preprocess a source file
src/ui/SimpleProvincePanel.cpp.i:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/mechanica_imperii.dir/build.make CMakeFiles/mechanica_imperii.dir/src/ui/SimpleProvincePanel.cpp.i
.PHONY : src/ui/SimpleProvincePanel.cpp.i

src/ui/SimpleProvincePanel.s: src/ui/SimpleProvincePanel.cpp.s
.PHONY : src/ui/SimpleProvincePanel.s

# target to generate assembly for a file
src/ui/SimpleProvincePanel.cpp.s:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/mechanica_imperii.dir/build.make CMakeFiles/mechanica_imperii.dir/src/ui/SimpleProvincePanel.cpp.s
.PHONY : src/ui/SimpleProvincePanel.cpp.s

src/ui/TechnologyInfoWindow.o: src/ui/TechnologyInfoWindow.cpp.o
.PHONY : src/ui/TechnologyInfoWindow.o

# target to build an object file
src/ui/TechnologyInfoWindow.cpp.o:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/mechanica_imperii.dir/build.make CMakeFiles/mechanica_imperii.dir/src/ui/TechnologyInfoWindow.cpp.o
.PHONY : src/ui/TechnologyInfoWindow.cpp.o

src/ui/TechnologyInfoWindow.i: src/ui/TechnologyInfoWindow.cpp.i
.PHONY : src/ui/TechnologyInfoWindow.i

# target to preprocess a source file
src/ui/TechnologyInfoWindow.cpp.i:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/mechanica_imperii.dir/build.make CMakeFiles/mechanica_imperii.dir/src/ui/TechnologyInfoWindow.cpp.i
.PHONY : src/ui/TechnologyInfoWindow.cpp.i

src/ui/TechnologyInfoWindow.s: src/ui/TechnologyInfoWindow.cpp.s
.PHONY : src/ui/TechnologyInfoWindow.s

# target to generate assembly for a file
src/ui/TechnologyInfoWindow.cpp.s:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/mechanica_imperii.dir/build.make CMakeFiles/mechanica_imperii.dir/src/ui/TechnologyInfoWindow.cpp.s
.PHONY : src/ui/TechnologyInfoWindow.cpp.s

src/ui/Toast.o: src/ui/Toast.cpp.o
.PHONY : src/ui/Toast.o

# target to build an object file
src/ui/Toast.cpp.o:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/mechanica_imperii.dir/build.make CMakeFiles/mechanica_imperii.dir/src/ui/Toast.cpp.o
.PHONY : src/ui/Toast.cpp.o

src/ui/Toast.i: src/ui/Toast.cpp.i
.PHONY : src/ui/Toast.i

# target to preprocess a source file
src/ui/Toast.cpp.i:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/mechanica_imperii.dir/build.make CMakeFiles/mechanica_imperii.dir/src/ui/Toast.cpp.i
.PHONY : src/ui/Toast.cpp.i

src/ui/Toast.s: src/ui/Toast.cpp.s
.PHONY : src/ui/Toast.s

# target to generate assembly for a file
src/ui/Toast.cpp.s:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/mechanica_imperii.dir/build.make CMakeFiles/mechanica_imperii.dir/src/ui/Toast.cpp.s
.PHONY : src/ui/Toast.cpp.s

src/utils/RandomGenerator.o: src/utils/RandomGenerator.cpp.o
.PHONY : src/utils/RandomGenerator.o

# target to build an object file
src/utils/RandomGenerator.cpp.o:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/mechanica_imperii.dir/build.make CMakeFiles/mechanica_imperii.dir/src/utils/RandomGenerator.cpp.o
.PHONY : src/utils/RandomGenerator.cpp.o

src/utils/RandomGenerator.i: src/utils/RandomGenerator.cpp.i
.PHONY : src/utils/RandomGenerator.i

# target to preprocess a source file
src/utils/RandomGenerator.cpp.i:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/mechanica_imperii.dir/build.make CMakeFiles/mechanica_imperii.dir/src/utils/RandomGenerator.cpp.i
.PHONY : src/utils/RandomGenerator.cpp.i

src/utils/RandomGenerator.s: src/utils/RandomGenerator.cpp.s
.PHONY : src/utils/RandomGenerator.s

# target to generate assembly for a file
src/utils/RandomGenerator.cpp.s:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/mechanica_imperii.dir/build.make CMakeFiles/mechanica_imperii.dir/src/utils/RandomGenerator.cpp.s
.PHONY : src/utils/RandomGenerator.cpp.s

# Help Target
help:
	@echo "The following are some of the valid targets for this Makefile:"
	@echo "... all (the default if no target is provided)"
	@echo "... clean"
	@echo "... depend"
	@echo "... edit_cache"
	@echo "... install"
	@echo "... install/local"
	@echo "... install/strip"
	@echo "... list_install_components"
	@echo "... rebuild_cache"
	@echo "... mechanica_imperii"
	@echo "... test_enhanced_config"
	@echo "... test_scenario_demo"
	@echo "... apps/main_minimal.o"
	@echo "... apps/main_minimal.i"
	@echo "... apps/main_minimal.s"
	@echo "... apps/test_enhanced_config.o"
	@echo "... apps/test_enhanced_config.i"
	@echo "... apps/test_enhanced_config.s"
	@echo "... apps/test_scenario_demo.o"
	@echo "... apps/test_scenario_demo.i"
	@echo "... apps/test_scenario_demo.s"
	@echo "... src/core/ECS/ComponentAccessManager.o"
	@echo "... src/core/ECS/ComponentAccessManager.i"
	@echo "... src/core/ECS/ComponentAccessManager.s"
	@echo "... src/core/ECS/MessageBus.o"
	@echo "... src/core/ECS/MessageBus.i"
	@echo "... src/core/ECS/MessageBus.s"
	@echo "... src/core/threading/ThreadedSystemManager.o"
	@echo "... src/core/threading/ThreadedSystemManager.i"
	@echo "... src/core/threading/ThreadedSystemManager.s"
	@echo "... src/game/administration/AdministrativeComponents.o"
	@echo "... src/game/administration/AdministrativeComponents.i"
	@echo "... src/game/administration/AdministrativeComponents.s"
	@echo "... src/game/administration/AdministrativeOfficial.o"
	@echo "... src/game/administration/AdministrativeOfficial.i"
	@echo "... src/game/administration/AdministrativeOfficial.s"
	@echo "... src/game/administration/AdministrativeSystem.o"
	@echo "... src/game/administration/AdministrativeSystem.i"
	@echo "... src/game/administration/AdministrativeSystem.s"
	@echo "... src/game/ai/AIAttentionManager.o"
	@echo "... src/game/ai/AIAttentionManager.i"
	@echo "... src/game/ai/AIAttentionManager.s"
	@echo "... src/game/ai/AIDirector.o"
	@echo "... src/game/ai/AIDirector.i"
	@echo "... src/game/ai/AIDirector.s"
	@echo "... src/game/ai/InformationPropagationSystem.o"
	@echo "... src/game/ai/InformationPropagationSystem.i"
	@echo "... src/game/ai/InformationPropagationSystem.s"
	@echo "... src/game/ai/NationAI.o"
	@echo "... src/game/ai/NationAI.i"
	@echo "... src/game/ai/NationAI.s"
	@echo "... src/game/config/ConfigHelpers.o"
	@echo "... src/game/config/ConfigHelpers.i"
	@echo "... src/game/config/ConfigHelpers.s"
	@echo "... src/game/config/GameConfig.o"
	@echo "... src/game/config/GameConfig.i"
	@echo "... src/game/config/GameConfig.s"
	@echo "... src/game/diplomacy/DiplomacyComponents.o"
	@echo "... src/game/diplomacy/DiplomacyComponents.i"
	@echo "... src/game/diplomacy/DiplomacyComponents.s"
	@echo "... src/game/diplomacy/DiplomacySystem.o"
	@echo "... src/game/diplomacy/DiplomacySystem.i"
	@echo "... src/game/diplomacy/DiplomacySystem.s"
	@echo "... src/game/diplomacy/DiplomacySystemSerialization.o"
	@echo "... src/game/diplomacy/DiplomacySystemSerialization.i"
	@echo "... src/game/diplomacy/DiplomacySystemSerialization.s"
	@echo "... src/game/economy/EconomicComponents.o"
	@echo "... src/game/economy/EconomicComponents.i"
	@echo "... src/game/economy/EconomicComponents.s"
	@echo "... src/game/economy/EconomicPopulationBridge.o"
	@echo "... src/game/economy/EconomicPopulationBridge.i"
	@echo "... src/game/economy/EconomicPopulationBridge.s"
	@echo "... src/game/economy/EconomicPopulationBridgeSerialization.o"
	@echo "... src/game/economy/EconomicPopulationBridgeSerialization.i"
	@echo "... src/game/economy/EconomicPopulationBridgeSerialization.s"
	@echo "... src/game/economy/EconomicSystem.o"
	@echo "... src/game/economy/EconomicSystem.i"
	@echo "... src/game/economy/EconomicSystem.s"
	@echo "... src/game/military/MilitaryComponents.o"
	@echo "... src/game/military/MilitaryComponents.i"
	@echo "... src/game/military/MilitaryComponents.s"
	@echo "... src/game/military/MilitaryDatabase_Utils.o"
	@echo "... src/game/military/MilitaryDatabase_Utils.i"
	@echo "... src/game/military/MilitaryDatabase_Utils.s"
	@echo "... src/game/military/MilitaryRecruitmentSystem.o"
	@echo "... src/game/military/MilitaryRecruitmentSystem.i"
	@echo "... src/game/military/MilitaryRecruitmentSystem.s"
	@echo "... src/game/military/MilitarySystem.o"
	@echo "... src/game/military/MilitarySystem.i"
	@echo "... src/game/military/MilitarySystem.s"
	@echo "... src/game/population/PopulationAggregator.o"
	@echo "... src/game/population/PopulationAggregator.i"
	@echo "... src/game/population/PopulationAggregator.s"
	@echo "... src/game/population/PopulationComponents.o"
	@echo "... src/game/population/PopulationComponents.i"
	@echo "... src/game/population/PopulationComponents.s"
	@echo "... src/game/population/PopulationEventProcessor.o"
	@echo "... src/game/population/PopulationEventProcessor.i"
	@echo "... src/game/population/PopulationEventProcessor.s"
	@echo "... src/game/population/PopulationFactory.o"
	@echo "... src/game/population/PopulationFactory.i"
	@echo "... src/game/population/PopulationFactory.s"
	@echo "... src/game/population/PopulationSystem.o"
	@echo "... src/game/population/PopulationSystem.i"
	@echo "... src/game/population/PopulationSystem.s"
	@echo "... src/game/population/PopulationUtils.o"
	@echo "... src/game/population/PopulationUtils.i"
	@echo "... src/game/population/PopulationUtils.s"
	@echo "... src/game/realm/RealmComponents.o"
	@echo "... src/game/realm/RealmComponents.i"
	@echo "... src/game/realm/RealmComponents.s"
	@echo "... src/game/realm/RealmManager.o"
	@echo "... src/game/realm/RealmManager.i"
	@echo "... src/game/realm/RealmManager.s"
	@echo "... src/game/scenario/ScenarioSystem.o"
	@echo "... src/game/scenario/ScenarioSystem.i"
	@echo "... src/game/scenario/ScenarioSystem.s"
	@echo "... src/game/technology/TechnologySystem.o"
	@echo "... src/game/technology/TechnologySystem.i"
	@echo "... src/game/technology/TechnologySystem.s"
	@echo "... src/game/technology/TechnologyUtils.o"
	@echo "... src/game/technology/TechnologyUtils.i"
	@echo "... src/game/technology/TechnologyUtils.s"
	@echo "... src/game/time/TimeComponents.o"
	@echo "... src/game/time/TimeComponents.i"
	@echo "... src/game/time/TimeComponents.s"
	@echo "... src/game/time/TimeManagementSystem.o"
	@echo "... src/game/time/TimeManagementSystem.i"
	@echo "... src/game/time/TimeManagementSystem.s"
	@echo "... src/ui/AdministrativeUI.o"
	@echo "... src/ui/AdministrativeUI.i"
	@echo "... src/ui/AdministrativeUI.s"
	@echo "... src/ui/MainMenuUI.o"
	@echo "... src/ui/MainMenuUI.i"
	@echo "... src/ui/MainMenuUI.s"
	@echo "... src/ui/PerformanceWindow.o"
	@echo "... src/ui/PerformanceWindow.i"
	@echo "... src/ui/PerformanceWindow.s"
	@echo "... src/ui/PopulationInfoWindow.o"
	@echo "... src/ui/PopulationInfoWindow.i"
	@echo "... src/ui/PopulationInfoWindow.s"
	@echo "... src/ui/SimpleProvincePanel.o"
	@echo "... src/ui/SimpleProvincePanel.i"
	@echo "... src/ui/SimpleProvincePanel.s"
	@echo "... src/ui/TechnologyInfoWindow.o"
	@echo "... src/ui/TechnologyInfoWindow.i"
	@echo "... src/ui/TechnologyInfoWindow.s"
	@echo "... src/ui/Toast.o"
	@echo "... src/ui/Toast.i"
	@echo "... src/ui/Toast.s"
	@echo "... src/utils/RandomGenerator.o"
	@echo "... src/utils/RandomGenerator.i"
	@echo "... src/utils/RandomGenerator.s"
.PHONY : help



#=============================================================================
# Special targets to cleanup operation of make.

# Special rule to run CMake to check the build system integrity.
# No rule that depends on this can have commands that come from listfiles
# because they might be regenerated.
cmake_check_build_system:
	$(CMAKE_COMMAND) -S$(CMAKE_SOURCE_DIR) -B$(CMAKE_BINARY_DIR) --check-build-system CMakeFiles/Makefile.cmake 0
.PHONY : cmake_check_build_system

